FROM node:20-alpine

WORKDIR /app

COPY package.json ./
# COPY package-lock.json ./
# COPY pnpm-lock.yaml ./
# COPY yarn.lock ./
# COPY bun.lockb ./
# COPY nuxt.lock ./
# COPY turbo.lock ./
# COPY pnpm-workspace.yaml ./
# COPY pnpm-workspace.yaml ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

